gestioncongees/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views
from .views import custom_logout



app_name = 'core'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('listUser/', views.getUser, name='getUser'),
    path('adduser/', views.adduser, name='adduser'),
    path('logout/', custom_logout, name='custom_logout'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/editetat/', views.editstatus, name='editstatus'),
]

gestioncongees/gestioncongees/urls.py
from django.contrib import admin
from django.urls import include, path
#to upload image with this trick 
from django.conf import settings
from django.conf.urls.static import static
#####

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('demande/', include('demandeCongee.urls')),
    path('taches/', include('tache.urls')),
    path('conversations/', include('conversation.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestioncongees/tache/urls.py
from django.urls import path
from . import views

app_name = 'tache'

urlpatterns = [
    path('tache_list/', views.ListTache, name='ListTache'),
    path('addTache/', views.addTache, name='addTache'),
    path('<int:pk>/edit/', views.editTache, name='editTache'),
    path('<int:pk>/delete/', views.deleteTache, name='deleteTache'),

]

gestioncongees/tache/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Tache(models.Model):
    STATUS_CHOICES = (
        ('open', 'Open'),
        ('encours', 'EnCours'),
        ('terminer', 'Terminer')
    )
    class Meta:
        verbose_name_plural = 'tache'

    user_id = models.ForeignKey(User, related_name="tache", on_delete=models.CASCADE)
    titre = models.CharField(max_length=255)
    duree = models.IntegerField()
    etat = models.CharField(choices=STATUS_CHOICES,max_length=10, default="open")
    created_at = models.DateTimeField(auto_now_add=True)

gestioncongees/tache/forms.py
from django import forms
from .models import Tache

INPUT_CLASSES = 'w-full py-4 px-6 rounded-md border'

class AddTachForm(forms.ModelForm):
    class Meta:
        model = Tache
        fields = ('user_id', 'titre', 'duree')
        widgets = {
            'user_id': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),            
            'titre': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'duree': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditTache(forms.ModelForm):
    class Meta:
        model = Tache
        fields = ('user_id', 'titre', 'duree')
        widgets = {
            'user_id': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),            
            'titre': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'duree': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

gestioncongees/tache/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from .forms import AddTachForm, EditTache

from .models import Tache

# Create your views here.
def ListTache(request):
    taches = Tache.objects.all().order_by('-created_at')
    
    return render(request, 'tache/listTaches.html',{
         'taches' : taches
    })


@login_required
def addTache(request):
    if request.method == 'POST':
        form = AddTachForm(request.POST)
        if form.is_valid():
            tach = form.save(commit=False)
            tach.save()
            return redirect('/taches/tache_list')
    else:
        form = AddTachForm()
              
    return render(request, 'tache/addTache.html', {
        'form' : form,
        'title' : 'Ajouter une tache ',
    })

@login_required
def editTache(request, pk):
    edittache = get_object_or_404(Tache, pk=pk)
    if request.method == 'POST':
       form = EditTache(request.POST, instance=edittache)
       if form.is_valid():
           edittache.save()
           return redirect('tache:ListTache')
    else:
        form = EditTache(instance=edittache)

    return render(request, 'tache/addTache.html', {
        'form' : form,
        'title' : 'Edit Tache'
    })

@login_required
def deleteTache(request, pk):
    Del_tache = get_object_or_404(Tache, pk=pk)
    Del_tache.delete()

    return redirect('tache:ListTache')

gestioncongees/tache/templates/tache/addTache.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="w-4/5 p-10 shadow-xl mx-auto float-right">
<h1 class="mb-6 text-3xl">{{ title }}</h1>
<!-- "multipart/form-data" need this to can upload images-->
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class=" w-full mt-6 py-2 px-5 text-md bg-teal-400 hover:bg-teal-700 rounded-md text-white">Ajouter</button>
</form>
</div>
{% endblock %}

gestioncongees/tache/templates/tache/listTaches.html
{% extends 'core/base.html' %}

{% block title %} List des Taches {% endblock %}

{% block content %}
<div class="w-4/5 py-5  mx-auto float-right">
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg px-5 py-5">
      <a href="{% url 'tache:addTache' %}" class="font-semibold hover:text-green-500" > + Ajouter Tache </a>
       <div class="pb-4 bg-white dark:bg-gray-900">
           <label for="filterName" class="sr-only">Search</label>
           <div class="relative mt-1">
               <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                   <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                       <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                   </svg>
               </div>
               <input type="text" id="filterName" class="block pt-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Filter username...">
           </div>
       </div>
       {% if request.user.role == admin %}
       <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
           <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
               <tr>
                   <th scope="col" class="p-4">
                       <div class="flex items-center">
                           <input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                           <label for="checkbox-all-search" class="sr-only">checkbox</label>
                       </div>
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Affecter a 
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Titre
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Duré (j)
                   </th>
                   <th scope="col" class="px-6 py-3">
                       D.creation
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Etat
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Actions
                   </th>
               </tr>
           </thead>
           <tbody>
               {% for tach in taches %}
               <tr class="bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-600">
                   <td class="w-4 p-4">
                       <div class="flex items-center">
                           <input id="checkbox-table-3" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                           <label for="checkbox-table-3" class="sr-only">checkbox</label>
                       </div>
                   </td>
   
                   <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                       {{ tach.user_id }}  
                   </td>
                   <td class="px-6 py-4">
                       {{tach.titre}}
                   </td>
                   <td class="px-6 py-4">
                       {{tach.duree}}
                   </td>
                   <td class="px-6 py-4">
                    {{tach.created_at}}
                   </td>
                   <td class="px-6 py-4 {% if tach.etat == 'open' %} text-red-600 {% elif tach.etat == 'encours'  %} text-yellow-600  {% else %} text-green-600 {% endif %} font-bold">
                       {{tach.etat}}

                      </div>
                   </td>
                   <td class="px-6 py-4">
                       <a href="{% url 'tache:editTache' tach.id %}" class="font-medium text-green-600 dark:text-green-500 hover:underline  {% if tach.etat == 'terminer' %} hidden {% endif %}" >Edit</a>
                       <a href="{% url 'tache:deleteTache' tach.id %}" class="font-medium text-red-600 dark:text-blue-500 hover:underline">Supprimer</a>
                   </td>
               </tr>
               {% endfor %}
           </tbody>
       </table>
       {% endif %}
   </div>
</div>
{% endblock %}