gestioncongees/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.conver, name='conver'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:user_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/delete/', views.deleteconv, name='deleteconv'),

]

gestioncongees/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views
from .views import custom_logout



app_name = 'core'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('listUser/', views.getUser, name='getUser'),
    path('adduser/', views.adduser, name='adduser'),
    path('logout/', custom_logout, name='custom_logout'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/editetat/', views.editstatus, name='editstatus'),
]

gestioncongees/gestioncongees/urls.py
from django.contrib import admin
from django.urls import include, path
#to upload image with this trick 
from django.conf import settings
from django.conf.urls.static import static
#####

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('demande/', include('demandeCongee.urls')),
    path('taches/', include('tache.urls')),
    path('conversations/', include('conversation.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestioncongees/conversation/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Conversation(models.Model):
    members = models.ManyToManyField(User, related_name='conversations',)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_at',)
    

class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE)

gestioncongees/conversation/forms.py
from django import forms
from .models import ConversationMessage

class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-full py-2 px-6 rounded-xl border'
            })
        }

gestioncongees/conversation/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Conversation
from .forms import ConversationMessageForm
from django.contrib.auth.models import User

# Create your views here.
@login_required
def conver(request):
    conversations = Conversation.objects.filter(members__in=[request.user.id])
    
    return render(request, 'conversation/conversation.html', {
        'conversations': conversations
    }) 


@login_required
def new_conversation(request,user_pk):
    user = get_object_or_404(User, pk=user_pk)

    conversations = Conversation.objects.filter(members=user).filter(members__in=[request.user.id])

    if conversations:
        return redirect('conversation:detail', pk=conversations.first().id)

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation = Conversation.objects.create()
            conversation.members.add(request.user)
            conversation.members.add(user)

            conversation.save()

            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            return redirect('conversation:conver')
    else:
        form = ConversationMessageForm()
    
    return render(request, 'conversation/new.html', {
        'form': form
    })


@login_required
def detail(request, pk):
    conversation = Conversation.objects.filter(members__in=[request.user.id]).get(pk=pk)

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            conversation.save()

            return redirect('conversation:detail', pk=pk)
    else:
        form = ConversationMessageForm()

    return render(request, 'conversation/detail.html', {
        'conversation': conversation,
        'form': form
    })

@login_required
def deleteconv(request, pk):
    Del_dec = get_object_or_404(Conversation, pk=pk)
    Del_dec.delete()

    return redirect('/conversations/')

gestioncongees/conversation/templates/conversation/conversation.html
{% extends 'core/base.html' %}

{% block title %}Conversations{% endblock %}

{% block content %}
<div class="w-3/5 mx-auto p-6 rounded-xl  overflow-x-auto shadow-md">

<h1 class="mb-6 text-3xl">Conversations</h1>

<div class="space-y-6">
    <div class="pb-4 bg-white dark:bg-gray-900">
        <label for="filterName" class="sr-only">Search</label>
        <div class="relative mt-1">
            <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
            </div>
            <input type="text" id="filterName" class="block pt-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
        </div>
    </div>
    {% for conversation in conversations %}
    <div class="py-1">
        {% if request.user.username == 'chehir' %}
        <a href="{% url 'conversation:deleteconv' conversation.id %}" class="font-medium text-red-600 dark:text-blue-500 hover:underline float-right px-5 py-20"><svg xmlns="http://www.w3.org/2000/svg" fill="#ff0000" height="18" width="16" viewBox="0 0 440 500"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.7 23.7 0 0 0 -21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0 -16-16zM53.2 467a48 48 0 0 0 47.9 45h245.8a48 48 0 0 0 47.9-45L416 128H32z"/></svg></a>
        {% endif %}
        <a href="{% url 'conversation:detail' conversation.id %}">
            <div class="p-6 flex bg-gray-100 rounded-xl">
                <div class="pr-6">
                    {% for member in conversation.members.all %}
                    {% if member != request.user %}
                    <img src="{{member.photo.url}}" alt="errors" class="w-16 md:w-32 max-w-full max-h-full rounded-xl">
                    {% endif %}
                    {% endfor %}
                </div>

                <div>
                    {% for member in conversation.members.all %}
                        {% if member != request.user %}
                            <p class="mb-6"><strong class="text-xl">{{ member.username }}</strong> | {{ conversation.modified_at }}</p>
                            <p class="text-blue-700 text-xl">Conversation details
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                                </svg>
                            </p>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}

gestioncongees/conversation/templates/conversation/detail.html
{% extends 'core/base.html' %}

{% block title %}Conversation{% endblock %}

{% block content %}
<div class="w-3/5 mx-auto p-6 rounded-xl  overflow-x-auto shadow-md">
<h1 class="mb-6 text-3xl">Conversation</h1>

<div class="space-y-6">
    {% for message in conversation.messages.all %} 
        <div class="p-6 flex {% if message.created_by == request.user %}bg-blue-100{% else %}bg-gray-100{% endif %} rounded-xl">
            <div>
                <p class="mb-4"><strong>{{ message.created_by.username }}</strong> @ {{ message.created_at }}</p>
                <p>{{ message.content }}</p>
            </div>
        </div>
    {% endfor %}
</div>

<form method="post" action="." class="mt-6">
    {% csrf_token %}

    {{ form.as_p }}

    <button class="py-4 px-8 text-sm bg-teal-500 hover:bg-teal-700 rounded-md text-white">Send</button>
</form>
</div>
{% endblock %}

gestioncongees/conversation/templates/conversation/new.html
{% extends 'core/base.html' %}

{% block title %}New conversation{% endblock %}

{% block content %}
<div class="w-3/5 mx-auto p-6 rounded-xl  overflow-x-auto shadow-md">
<h1 class="mb-6 text-3xl">Nouvelle conversation</h1>

<form method="post" action=".">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
</form>
</div>
{% endblock %}