gestioncongees/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.conver, name='conver'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:user_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/delete/', views.deleteconv, name='deleteconv'),

]

gestioncongees/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views
from .views import custom_logout



app_name = 'core'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('listUser/', views.getUser, name='getUser'),
    path('adduser/', views.adduser, name='adduser'),
    path('logout/', custom_logout, name='custom_logout'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/editetat/', views.editstatus, name='editstatus'),
]

gestioncongees/demandeCongee/urls.py
from django.urls import path
from . import views

app_name = 'demandeCongee'

urlpatterns = [
    path('<int:pk>/demandeCong/', views.d_Congee, name='d_Congee'),
    path('listc/', views.ListConges, name='ListConges'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/<int:pk_demandeur>/editstat/', views.editstatus, name='editstatus'),
    path('<int:pk>/delete/', views.delete, name='delete')

]

gestioncongees/gestioncongees/urls.py
from django.contrib import admin
from django.urls import include, path
#to upload image with this trick 
from django.conf import settings
from django.conf.urls.static import static
#####

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('demande/', include('demandeCongee.urls')),
    path('taches/', include('tache.urls')),
    path('conversations/', include('conversation.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestioncongees/tache/urls.py
from django.urls import path
from . import views

app_name = 'tache'

urlpatterns = [
    path('tache_list/', views.ListTache, name='ListTache'),
    path('addTache/', views.addTache, name='addTache'),
    path('<int:pk>/edit/', views.editTache, name='editTache'),
    path('<int:pk>/delete/', views.deleteTache, name='deleteTache'),

]

gestioncongees/core/models.py
from django.db import models
from django.contrib.auth.models import User

class CustomUser(User):
    
    ROLES = [
        ('user', 'User'),
        ('admin', 'Admin'),
    ]

    role = models.CharField(max_length=10, choices=ROLES, default='user')
    sold = models.IntegerField(default = 24)
    
    def __str__(self):
        return self.username

gestioncongees/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import CustomUser
from django.contrib.auth.models import User


INPUT_CLASSES = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"

class LoginForm(AuthenticationForm):

        username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your username',
            'class' : 'w-full py-4 px-6 rounded-xl'
        }))
        
        password = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Your password',
            'class' : 'w-full py-4 px-6 rounded-xl'
        }))



class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username','first_name','last_name', 'email','photo','password1', 'password2','sold','role')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class' : INPUT_CLASSES
    }))
    
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'First Name',
        'class' : INPUT_CLASSES
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Last Name',
        'class' : INPUT_CLASSES
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email @',
        'class' : INPUT_CLASSES
    }))

    photo = forms.FileInput(attrs={
        'class': INPUT_CLASSES
    }),

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class' : INPUT_CLASSES
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class' : INPUT_CLASSES
    }))

    sold = forms.IntegerField( show_hidden_initial=True,initial=24)
     
    role = forms.CharField(initial='user', show_hidden_initial=True)

class EditUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','first_name','last_name', 'email','photo', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class' : INPUT_CLASSES
    }))
    
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'First Name',
        'class' : INPUT_CLASSES
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Last Name',
        'class' : INPUT_CLASSES
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email @',
        'class' : INPUT_CLASSES
    }))

    photo = forms.FileInput(attrs={
        'class': INPUT_CLASSES
    }),

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class' : INPUT_CLASSES
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class' : INPUT_CLASSES
    }))

gestioncongees/core/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .models import CustomUser

from .forms import EditUserForm, SignupForm
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from demandeCongee.models import Cangees
from tache.models import Tache
from conversation.models import Conversation


# Create your views here.
@login_required
def index(request):
    nbusers = User.objects.all()
    nbdemandes = Cangees.objects.all()
    nbtaches = Tache.objects.filter(etat = 'open')
    convcounts = Conversation.objects.all()

    return render(request, 'core/index.html',{
    'nbusers' : nbusers,
    'nbdemandes' : nbdemandes,
    'nbtaches' : nbtaches,
    'convcounts' : convcounts

    })

def contact(request):
    return render(request, 'core/contact.html')

def getUser(request):
    user = CustomUser.objects.all()
    return render(request, 'core/listUser.html', {
        'users' : user
    })
    

@login_required
def adduser(request):
    if request.method == 'POST':
        form = SignupForm(request.POST,request.FILES)
            
        if form.is_valid():
            form.save()
            return redirect('/listUser/')
    else:
        
        form = SignupForm()

    return render(request, 'core/adduser.html', {
        'form' : form,
        'title': 'Ajouter user'
    })


@login_required
def edit(request, pk):
    editc = get_object_or_404(CustomUser, pk=pk)
    if request.method == 'POST':
        form = EditUserForm(request.POST,request.FILES, instance=editc)
        if form.is_valid():
            editc.save()
            return redirect('/listUser/')
    else:
        form = EditUserForm(instance=editc)
    
    return render(request, 'core/adduser.html', {
        'form' : form,
        'title' : 'Modifier User',
    })

@login_required
def delete(request, pk):
    userd = get_object_or_404(CustomUser, pk=pk)
    userd.delete()

    return redirect('/listUser')




def custom_logout(request):
    logout(request)
    return redirect('/') 

@login_required
def editstatus(request,pk):
    editstatus = get_object_or_404(Tache, pk=pk)
    if request.method == 'POST':
        editstatus.etat = 'terminer'
        editstatus.save()
        return redirect('/index/')


    return render(request, 'tache/addTache.html', {
        'title': 'Approuver la tache ',
        'editstatus': editstatus,
    })

gestioncongees/core/templates/core/adduser.html
{% extends 'core/base.html' %}

{% block title %}Ajouter Utilisateurs{% endblock %}

{% block content %}
<div class="w-3/5 mx-auto p-6 rounded-xl  overflow-x-auto shadow-md">
    <h2 class="mb-2 text-2xl">{{ title }}</h2>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">User name </label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">First Name</label><br>
            {{ form.first_name }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Last Name</label><br>
            {{ form.last_name }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Photo</label><br>
            {{ form.photo }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>
        <span hidden>{{form.sold}}</span>
        <span hidden>{{form.role}}</span>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-2 px-6 text-sm bg-teal-500 hover:bg-teal-700 rounded-md text-white">+ Ajouter</button>
    </form>
</div>
{% endblock %}

gestioncongees/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

    <title>{% block title %} {% endblock %} | gestion des Congees </title>
</head>
<body>
   <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
      <a href="index/" class="text-xl font-semibold">TEST</a>

      <div class="space-x-6">
         {% if request.user.username != 'chehir'  %}
          <a href="{% url 'demandeCongee:d_Congee' request.user.id %}" class="text-sm font-semibold hover:text-green-500" > + Demander Congeés </a>
          {% endif %}
          <a href="{% url 'core:index' %}" class="px-6 py-3 text-sm font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
          <a href="{% url 'core:custom_logout' %}" class="px-6 py-3 text-sm font-semibold bg-red-500 text-white rounded hover:bg-red-700">LOGOUT</a>
        
      </div>
  </nav>
     <aside id="separator-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
        <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
           <ul class="space-y-2 font-medium">
            <h2 class=" ms-3 text-lg font-bold text-gray-500 hover:text-gray-500 px-5" >Bonjour Mr.{{ request.user }}</h2>
              <li>
                 <a href=" {% url 'core:index' %} " class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                       <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                       <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
                    </svg>
                    <span class="ms-3">Dashboard</span>
                 </a>
              </li>
              <li>
                 <a href="{% url 'demandeCongee:ListConges' %}" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                       <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"/>
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Demandes Cangés</span>
                 </a>
              </li>  
              {% if request.user.username == 'chehir'   %}
              <li>
                 <a href="{% url 'core:getUser' %}" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                       <path d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"/>
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Utilisateurs</span>
                 </a>
              </li>
              <li>
               <a href="{% url 'tache:ListTache' %}" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                   <path d="M5 5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707A2.96 2.96 0 0 0 .13 5H5Z"/>
                   <path d="M6.737 11.061a2.961 2.961 0 0 1 .81-1.515l6.117-6.116A4.839 4.839 0 0 1 16 2.141V2a1.97 1.97 0 0 0-1.933-2H7v5a2 2 0 0 1-2 2H0v11a1.969 1.969 0 0 0 1.933 2h12.134A1.97 1.97 0 0 0 16 18v-3.093l-1.546 1.546c-.413.413-.94.695-1.513.81l-3.4.679a2.947 2.947 0 0 1-1.85-.227 2.96 2.96 0 0 1-1.635-3.257l.681-3.397Z"/>
                   <path d="M8.961 16a.93.93 0 0 0 .189-.019l3.4-.679a.961.961 0 0 0 .49-.263l6.118-6.117a2.884 2.884 0 0 0-4.079-4.078l-6.117 6.117a.96.96 0 0 0-.263.491l-.679 3.4A.961.961 0 0 0 8.961 16Zm7.477-9.8a.958.958 0 0 1 .68-.281.961.961 0 0 1 .682 1.644l-.315.315-1.36-1.36.313-.318Zm-5.911 5.911 4.236-4.236 1.359 1.359-4.236 4.237-1.7.339.341-1.699Z"/>
                </svg>
                  <span class="flex-1 ms-3 whitespace-nowrap">List des Taches</span>
               </a>
            </li>
              {% endif %}
              <li>
               <a href="{% url 'conversation:conver' %}" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                  <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                     <path d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"/>
                  </svg>
                  <span class="flex-1 ms-3 whitespace-nowrap">Conversations</span>
                  <span class="inline-flex items-center justify-center w-3 h-3 p-3 ms-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300">{{convcounts.count}}</span>
               </a>
            </li>
           </ul>
        </div>
     </aside>
        {% block content %}
        {% endblock %}
  </body>
  <script>
   function filterTable() {
     var inputName = document.getElementById('filterName').value.toUpperCase();
     // Get other input values for additional columns
   
     var table = document.querySelector('table');
     var rows = table.querySelectorAll('tbody tr');
   
     rows.forEach(function (row) {
       var cells = row.querySelectorAll('td');
       var name = cells[1].innerText.toUpperCase();
       // Get other cell values for additional columns
   
       if (name.includes(inputName)) {
         row.style.display = '';
       } else {
         row.style.display = 'none';
       }
     });
   }
   
   // Attach the filterTable function to the input elements
   document.getElementById('filterName').addEventListener('input', filterTable);
   // Add similar listeners for other filter inputs
   </script>
</html>

gestioncongees/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
  <h1>Contact page</h1>
{% endblock %}

gestioncongees/core/templates/core/listUser.html
{% extends 'core/base.html' %}

{% block title %} Liste des utilisateurs {% endblock %}

{% block content %}
<div class="w-4/5 py-5  mx-auto float-right">
 <div class="relative overflow-x-auto shadow-md sm:rounded-lg px-5 py-5">
    <a href="{% url 'core:adduser' %}" class="font-semibold hover:text-green-500" > + Ajouter Utilisateur </a>

    <div class="pb-4 bg-white dark:bg-gray-900">
        <label for="filterName" class="sr-only">Search</label>
        <div class="relative mt-1">
            <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
            </div>
            <input type="text" id="filterName" class="block pt-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Filter username...">
        </div>
    </div>
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="p-4">
                    <div class="flex items-center">
                        <input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="checkbox-all-search" class="sr-only">checkbox</label>
                    </div>
                </th>
                <th scope="col" class="px-6 py-3">
                    Photo
               </th>
                <th scope="col" class="px-6 py-3">
                     Nom
                </th>
                <th scope="col" class="px-6 py-3">
                    Email
                </th>
                <th scope="col" class="px-6 py-3">
                    Prenom
                </th>
                <th scope="col" class="px-6 py-3">
                    Nom
                </th>
                <th scope="col" class="px-6 py-3">
                    sold congee
                </th>
                <th scope="col" class="px-6 py-3">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr class="bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-600">
                <td class="w-4 p-4">
                    <div class="flex items-center">
                        <input id="checkbox-table-3" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="checkbox-table-3" class="sr-only">checkbox</label>
                    </div>
                </td>
                <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <img class="w-10 h-10 rounded-full" src="{{user.photo.url}}" alt="problem !">
                </td>
                <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{ user.username}}
                </td>
                <td class="px-6 py-4">
                    {{user.email}}
                </td>
                <td class="px-6 py-4">
                    {{user.first_name}}
                </td>
                <td class="px-6 py-4">
                    {{user.last_name}}
                </td>
                <td class="px-6 py-4">
                    {{user.sold}} 
                </td>
                <td class="px-6 py-4">
                    <a href=" {% url 'core:edit' user.id %} " class="font-medium text-green-600 dark:text-green-500 hover:underline">Edit</a>
                    <a href="{% url 'core:delete' user.id %}" class="font-medium text-red-600 dark:text-blue-500 hover:underline">Remove</a>
                    <a href="{% url 'conversation:new' user.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Cantacter</a>

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}

gestioncongees/core/templates/core/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %} {% endblock %} | gestion des Congees </title>
</head>
<body>


{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">LogIn</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

</body>
</html>