gestioncongees/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views
from .views import custom_logout



app_name = 'core'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('listUser/', views.getUser, name='getUser'),
    path('adduser/', views.adduser, name='adduser'),
    path('logout/', custom_logout, name='custom_logout'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/editetat/', views.editstatus, name='editstatus'),
]

gestioncongees/demandeCongee/urls.py
from django.urls import path
from . import views

app_name = 'demandeCongee'

urlpatterns = [
    path('<int:pk>/demandeCong/', views.d_Congee, name='d_Congee'),
    path('listc/', views.ListConges, name='ListConges'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/<int:pk_demandeur>/editstat/', views.editstatus, name='editstatus'),
    path('<int:pk>/delete/', views.delete, name='delete')

]

gestioncongees/gestioncongees/urls.py
from django.contrib import admin
from django.urls import include, path
#to upload image with this trick 
from django.conf import settings
from django.conf.urls.static import static
#####

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('demande/', include('demandeCongee.urls')),
    path('taches/', include('tache.urls')),
    path('conversations/', include('conversation.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestioncongees/demandeCongee/models.py
from django.db import models

from core.models import CustomUser
from django.contrib.auth.models import User

class Cangees(models.Model):
    demandeur = models.ForeignKey(User, related_name= 'Cangees', on_delete=models.CASCADE)
    sujet = models.CharField(max_length=255)
    dure = models.IntegerField()
    certif = models.FileField(upload_to='certif', blank=True, null=True)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

gestioncongees/demandeCongee/forms.py
from django import forms
from .models import Cangees

INPUT_CLASSES = 'w-full py-4 px-6 rounded-md border'


class CongeForm(forms.ModelForm):
    class Meta:
        model = Cangees
        fields = ('sujet', 'dure', 'certif',)
        widgets = {
            'demandeur': forms.CharField(show_hidden_initial= True),
            'sujet': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'dure': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'certif': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            
        }


class EditCongeForm(forms.ModelForm):
    class Meta:
        model = Cangees
        fields = ('sujet', 'dure', 'certif')
        widgets = {
            'sujet': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'dure': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'certif': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            
        }

gestioncongees/demandeCongee/views.py
from django.shortcuts import redirect, render, get_object_or_404

from .models import Cangees

from .forms import CongeForm, EditCongeForm
from django.contrib.auth.decorators import login_required
from core.models import CustomUser

# Create your views here.
@login_required
def ListConges(request):
    congees = Cangees.objects.all().order_by('-created_at')
    return render(request, 'demandeCongee/listCongees.html',{
         'congees' : congees
    })


@login_required
def d_Congee(request,pk):
    alert_message = ""
    user_id = get_object_or_404(CustomUser, pk=pk)
    if request.method == 'POST':
        form = CongeForm(request.POST, request.FILES)
        if form.is_valid():
           cong = form.save(commit=False)
           if cong.dure <=  user_id.sold:
              cong.demandeur = request.user
              cong.save()
              return redirect('/demande/listc/')
           else:
              alert_message = "vous avez deppaser votre sold des congées !"
    else: 
        form = CongeForm()
    
    return render(request, 'demandeCongee/dCongee.html', {
        'form' : form,
        'title' : 'Demande ',
        'alert_message': alert_message
    })

@login_required
def edit(request, pk):
    editdemande = get_object_or_404(Cangees, pk=pk)
    if request.method == 'POST':
        form = EditCongeForm(request.POST, instance=editdemande)
        if form.is_valid():
            editdemande.save()
            return redirect('/demande/listc/')
    else:
        form = EditCongeForm(instance=editdemande)
    
    return render(request, 'demandeCongee/dCongee.html', {
        'form' : form,
        'title' : 'Edit Demande',
    })




@login_required
def delete(request, pk):
    Del_demande = get_object_or_404(Cangees, pk=pk)
    Del_demande.delete()

    return redirect('/demande/listc/')


@login_required
def editstatus(request,pk,pk_demandeur):
    editstatus = get_object_or_404(Cangees, pk=pk)
    editsold = get_object_or_404(CustomUser, id = pk_demandeur )

    if request.method == 'POST':
        editstatus.status = True
        editstatus.save()

        newsold = editsold.sold - editstatus.dure
        editsold.sold = newsold 
        editsold.save()
        return redirect('/demande/listc/')


    return render(request, 'demandeCongee/dCongee.html', {
        'title': 'Approuver la demande ',
        'editstatus': editstatus,
    })

gestioncongees/demandeCongee/templates/demandeCongee/dCongee.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
{% if alert_message %}
<script>
    alert("{{ alert_message|safe }}");
</script>
{% endif %}
<div class="w-4/5 p-10 shadow-xl mx-auto float-right">
<h1 class="mb-6 text-3xl">{{ title }}</h1>
<!-- "multipart/form-data" need this to can upload images-->
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
</div>
{% endblock %}

gestioncongees/demandeCongee/templates/demandeCongee/listCongees.html
{% extends 'core/base.html' %}

{% block title %} List des Demande {% endblock %}

{% block content %}
<div class="w-4/5 py-5  mx-auto float-right ">
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg px-5 py-5">
   
       <div class="pb-4 bg-white dark:bg-gray-900">
           <label for="filterName" class="sr-only">Search</label>
           <div class="relative mt-1">
               <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                   <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                       <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                   </svg>
               </div>
               <input type="text" id="filterName" class="block pt-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Filter username...">
           </div>
       </div>
       {% if request.user.username == 'chehir' %}
       <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
           <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
               <tr>
                   <th scope="col" class="p-4">
                       <div class="flex items-center">
                           <input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                           <label for="checkbox-all-search" class="sr-only">checkbox</label>
                       </div>
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Demandeur
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Sujet
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Duré (j)
                   </th>
                   <th scope="col" class="px-6 py-3">
                       sold congé disponible (j)
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Certificat medical
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Statut
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Date
                   </th>
                   <th scope="col" class="px-6 py-3">
                       Actions
                   </th>
               </tr>
           </thead>
           <tbody>
               {% for cong in congees %}
               <tr class="bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-600">
                   <td class="w-4 p-4">
                       <div class="flex items-center">
                           <input id="checkbox-table-3" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                           <label for="checkbox-table-3" class="sr-only">checkbox</label>
                       </div>
                   </td>
   
                   <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                       {{ cong.demandeur.first_name}}  {{ cong.demandeur.last_name}}
                   </td>
                   <td class="px-6 py-4">
                       {{cong.sujet}}
                   </td>
                   <td class="px-6 py-4">
                       {{cong.dure}}
                   </td>
                   <td class="px-6 py-4">
                       {{cong.demandeur.sold}}
                   </td>
                   <td class="px-6 py-4">
                       {{cong.certif}}    
                   </td>
                   <td class="px-6 py-4 {% if cong.status != False %} text-green-600 {% else %} text-yellow-600 {% endif %} font-bold">
                        {% if cong.status != False  %}
                        {{'Approuver'}}
                        {% else %}
                        {{'Attente'}}
                        {% endif %}
                   </td>
                   <td class="px-6 py-4">
                    {{cong.created_at}}    
                   </td>
                   <td class="px-6 py-4">
                       <a href="{% url 'demandeCongee:editstatus' cong.id cong.demandeur.id %}" class="font-medium text-green-600 dark:text-green-500 hover:underline {% if cong.status != False %} hidden {% endif %}" >Approuver</a>
                       <a href="{% url 'demandeCongee:delete' cong.id %}" class="font-medium text-red-600 dark:text-blue-500 hover:underline">Supprimer</a>
                   </td>
               </tr>
               {% endfor %}
           </tbody>
       </table>
       {% endif %}
       {% for conge in congees %}
       {% if request.user.username != 'chehir' and request.user.username == conge.demandeur.username %}
       <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
           <li class="py-3 sm:py-4">
                 <div class="flex items-center">
                    <div class="flex-1 min-w-0 ms-4">
                       <p class="text-lg font-medium text-gray-900 truncate dark:text-white">
                            Sujet: {{conge.sujet}}
                       </p>
                       <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                             Dure: {{conge.dure}} Jours
                       </p>
                    </div>
                    <div class="inline-flex items-center {% if conge.status != False %} text-green-600 {% else %} text-yellow-600 {% endif %} text-base font-semibold text-gray-900 dark:text-white">
                      {% if conge.status != False  %}
                      {{'Approuver'}}
                      {% else %}
                      {{'En Attente'}}
                      {% endif %}
                    </div>
                 </div>
                 <a href="{% url 'demandeCongee:edit' conge.id %}" class="inline-block mt-6 px-2 1text-sm font-semibold bg-teal-500 text-white rounded-md {% if conge.status != False %} hidden {% endif %}">Edit Demande</a>
                </li>
        </ul>
       </div>
       {% endif %}
       {% endfor %}
   </div>
</div>
{% endblock %}